input {
  # Receive customer tracking events from Kafka
  kafka {
    bootstrap_servers => "host.docker.internal:29092"
    topics => ["customer-events-raw"]
    group_id => "logstash-es-sink-group"
    codec => "json"
    auto_offset_reset => "earliest"
    decorate_events => "basic"
  }
}

filter {
  # Process Customer Tracking events
  date {
    match => [ "event_time", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://ecomflow-elasticsearch:9200"]
    index => "customer-events-raw-%{+YYYY.MM.dd}"
    document_id => "%{acc_id}_%{session_id}_%{event_time}"
  }
  
  stdout {
    codec => rubydebug
  }
}
